# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true
  cyclop:
    max-complexity: 12 # TODO check if feasible to simplify

linters:
  enable-all: true
  disable:
    - err113
    - lll
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - forcetypeassert
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - exhaustruct
    - nonamedreturns
    - testableexamples
    - dupword
    - depguard
    - tagalign
    - execinquery
    - mnd
    - testifylint

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - staticcheck
      path: ".go"
      text: "\"io/ioutil\" has been deprecated since" # Keeping backwards compatibility with go1.13.
    - linters:
        - gomnd
        - mnd
        - goconst
        - noctx
        - funlen
        - dupl
        - structcheck
        - unused
        - unparam
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
        - gosec
      path: "example_"
    - linters:
        - revive
      text: "unused-parameter: parameter"

